endpoint:
  url: http://httpbin.org
#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,env,prometheus

server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

springdoc:
  packages-to-scan: org.crm.controller
  paths-to-match: /**
  api-docs:
    path: /api-docs

logger:
  name: ${rootProject.name}
  version: ${version}
  type: microservices
  tags: template, service
  zone: localhost
  level: DEBUG
