do 
$$ 
DECLARE 
URL_ALL_BIS_X_ADJUST_REASONS_FIELD bigint = (select id from db.tdictionary_instance.ref_id where ref_id = 'URL.ALL.BIS.X_ADJUST_REASONS'); 
SZT_ALL_BIS_X_ADJUST_REASONS_FIELD bigint = (select id from db.tdictionary_instance.ref_id where ref_id = 'SZT.ALL.BIS.X_ADJUST_REASONS'); 
BEGIN 
INSERT INTO myDatabase.mySchema (ext_id, title, is_visible, tdictionary_instance_id, create_date, update_date) 
VALUES 
('288', 'Возврат оплаты ШС (САПРП)', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('287', 'Оплата ШС (САПРП)', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('286', 'Взаимозачет. Выкуп оборудования', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('285', 'Перенос ДС в оплату рассрочки', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('284', 'Программа лояльности скидка 100%', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('283', 'Программа лояльности скидка 90%', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('282', 'Программа лояльности скидка 60%', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('281', 'Программа лояльности скидка 30%', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('268', 'Перерасчет начислений по решению суда', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('267', 'Перенос начислений', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('266', 'Начисления за оказанные услуги', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('265', 'Начисления невозможные к взысканию', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('264', 'Начисления текущего периода', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('263', 'Перерасчет МСП', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('262', 'Отмена cкидки по услугам МГ/МН связи', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('261', 'Скидка по услугам МГ/МН связи', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('260', 'Восстановление списанной дебиторской задолженности', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('256', 'Бонус', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('255', 'Списание ДЗ  -  9 мая', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('254', 'Списание ДЗ по Претензии НСТ – ОРП', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('253', 'Списание ДЗ по Претензии НСТ – ГТП ЦБС', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('252', 'Списание ДЗ по Претензии НСТ – ОРП МРФ', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('251', 'Списание кредиторской задолженности', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('250', 'Списание дебиторской задолженности', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('213', 'Отмена возврата аванса через ЕРКЦ', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('212', 'Возврат аванса через ЕРКЦ', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('211', 'Отмена переноса/возврата аванса через ЕРКЦ', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('210', 'Перенос аванса через ЕРКЦ', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('200', 'Отмена платежа от ЕРКЦ', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('181', 'Отмена платежа от ЕИССД', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('161', 'Сторнирование платежа активации', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('155', 'Перерасчет. Ошибки отражения услуг в информационных системах', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('154', 'Передача коллектору оплаты, поступившей по договору цессии', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('153', 'Отзыв ДС по договору цессии', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('152', 'Поступление ДС по договору цессии', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('151', 'Возврат ДС в бухучет', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('150', 'Поступление ДС из бухучета', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('149', 'Возврат другому поставщику', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('148', 'Корректировка суммы платежа', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('147', '(Форм. доп. лист ЕКП) Перерасчет  ГТП ЦБС. Обращение абонента на 1-ю линию', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('146', 'Перерасчет  ГТП ЦБС. Обращение абонента на 1-ю линию ТП', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('145', 'Доначисление или сторнирование начислений. Сбой системы.', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('144', '(Форм. доп. лист ЕКП) Доначисление или сторнирование начислений. Сбой системы.', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('143', 'Обоснованный отказ абонента от начислений', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('142', '(Форм. доп. лист ЕКП)  Обоснованный отказ абонента от начислений.', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('141', 'Перерасчет. Ошибки тарификации.', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('140', 'Перерасчет по причине кабельного повреждения', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('122', 'Перенос аванса из CFE', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('121', 'Перевод аванса от другого поставщика', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('110', 'Возврат платежа через кассу или расчетный счет', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('109', 'Возврат другому поставщику', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('108', 'Перенос аванса в CFE', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('107', 'Благотворительность', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('106', 'Перенос с другого лицевого счета', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('105', 'Перенос на другой лицевой счет', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('104', 'Возврат клиенту через кассу или расчетный счет', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('103', 'Рекламная акция', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('102', 'Льгота оператора', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('101', 'Поступление ДС по ВХР', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('86', 'Прием платежа от клиента через дилера', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('85', 'Подключение абонента через дилера', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('84', 'Возврат дилером КЭО', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('83', 'Продажа КЭО дилеру', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('82', 'Возврат дилером SIM-карты', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('81', 'Продажа SIM-карты дилеру', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('61', '(Форм. доп. лист ЕКП) Перерасчет. Ошибки тарификации.', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('43', 'Отмена платежа', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('42', 'Удержание из зарплаты сотрудников', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('41', 'Взаимозачет', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('40', 'Корректировка платежа', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('3', 'Выдача бонуса', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('1', 'Обнуление баланса RT-клиента', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('0', '???', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('156', 'Биллинговая скидка', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('292', '(Резерв_Чалкова) Отмена взаимозачета по выкупу АО', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('291', '(Резерв_Чалкова) Взаимозачет по выкупу АО', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('446', 'Ош: Ошибки тарификации (сбой системы)', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('290', 'Перенос ДС в оплату рассрочки (Вывод по ВХР)', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('460', 'Автоматический перерасчет', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('453', 'Пр: Несанкционированный доступ 3-их лиц к услугам', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('452', 'Пр: Сверка с операторами / посредниками', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('450', 'Пр: По решению судебных и надзорных органов', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('445', 'Ош: Неправомерные начисления в период блокировки', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('444', 'Ош: Ошибки сотрудника ТБ', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('443', 'Ош: Ошибки тарификации (ИТ)', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('442', 'Ош: Несвоевременное назначение / снятие услуги', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('441', 'Ош: Ошибка при изменении условий договора', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('440', 'Ош: Ошибка при заведении новых ТП в ИС', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('432', 'АО: Изменение условий оплаты за оборудование', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('430', 'АО: Возврат/замена оборудования', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('420', 'Фин: Перенос начислений', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('412', 'Тех: Тестовое подключение', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('411', 'Тех: Некачественное оказание услуги', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('410', 'Тех: Отсутствие услуги', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('407', 'Ком: Услуги / доп. опции по акции', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('406', 'Ком: Форс-мажорные обстоятельства', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('405', 'Ком: Благотворительность', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('404', 'Ком: 9 мая', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('403', 'Ком: Доначисления за нарушения условий акции', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('402', 'Ком: Индивидуальная (разовая) корректировка', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('401', 'Ком: Маркетинговая активность', false, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('400', 'Ком: Изменение условий договора', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('321', 'Списание ДЗ по Претензии НСТ', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('303', 'Вывод ДС по ВХР', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('302', 'Поступление ДС по ВХР', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('301', 'Вывод ДС по ВХР', true, 'URL_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('145', 'Другие услуги телеграфной связи', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('143', 'Услуги связи по предоставлению в пользование телеграфных каналов связи (ВЗ)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('133', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('132', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ: 3. Ликвидация ЮЛ (ст.419 ГК РФ)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('131', 'Списание КЗ по прочим причинам', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('130', 'Списание КЗ свыше 3-х лет', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('129', 'Списание КЗ по акту  сверки', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('128', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ Банкротство юридического лица', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('127', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ по отказу в иске', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('126', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ по отказу конк. управляющего', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('125', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-62 сч (отчетный год или 36 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('124', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ по прочим причинам', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('123', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-62 сч (отчетный год или 36 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('122', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ по акту сверки', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('121', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-62 сч(отч.год или 36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('120', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ Невозможность взыскания по исполнительному листу', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('119', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ Сумма меньше порога подачи иска', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('118', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ Недостаточно документов для подачи иска', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('117', 'Просьба клиента', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('116', 'Ошибка зачисления', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('140413', 'clm140413', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99015', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во34,36,40)1.ИСИД(3 г,ст.196 ГК РФ)-76 сч(свыше 36 мес)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99014', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)3.Ликв.ЮЛ(ст.419 ГК РФ)-76 сч(отчетный год)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99013', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)7.Пос.суд.пр(ст.266 НК РФ)-76 сч(отчетнрый год)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99012', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)7.Пос.суд.пр(ст.266 НК РФ)-76 сч(24-36м.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99011', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)7.Пос.суд.пр(ст.266 НК РФ)-76 сч(12-24м.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99010', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)7.Пос.суд.пр(ст.266 НК РФ)-76 сч(12м.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99009', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)3.Ликв.ЮЛ(ст.419 ГК РФ)-76 сч(24-36 мес.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99008', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)3.Ликв.ЮЛ(ст.419 ГК РФ)-76 сч(12-24 мес.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99007', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)3.Ликв.ЮЛ(ст.419 ГК РФ)-76 сч(12 мес.до отч.года)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99006', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)2.Смерть гр(ст.418 ГК РФ)-76 сч(24-36 м.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99005', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)2.Смерть гр(ст.418 ГК РФ)-76 сч(12-24 м.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99004', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во 34,36,40)2.Смерть гр(ст.418 ГК РФ)-76 сч(12 м.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99003', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во34,36,40)1.ИСИД(3 г,ст.196 ГК РФ)-76 сч(24-36 мес.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99002', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во34,36,40)1.ИСИД(3 г,ст.196 ГК РФ)-76 сч(12-24 мес.до отч.г)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99001', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во34,36,40)1.ИСИД(3 г,ст.196 ГК РФ)-76 сч(12 мес.до отч.года)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88055', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-76 сч(нет докум.или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88054', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-76 сч(24-36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88053', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-76 сч(12-24 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88052', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-76 сч(12 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88051', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88050', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-62 сч(нет докум.или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88049', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-76 сч(нет докум.или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88048', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-76 сч(24-36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88047', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-76 сч(12-24 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88046', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-76 сч(12 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88045', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88044', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-62 сч(нет докум.или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88043', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва (ст.416 ГК РФ)-76 сч(нет докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88042', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва (ст.416 ГК РФ)-76 сч(24-36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88041', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва (ст.416 ГК РФ)-76 сч(12-24 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88040', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва (ст.416 ГК РФ)-76 сч(12 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88039', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва (ст.416 ГК РФ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88038', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва (ст.416 ГК РФ)-62 сч(нет докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88037', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-76 сч(нет.докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88036', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-76 сч(24-36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88035', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-76 сч(12-24 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88034', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-76 сч(12 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88033', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88032', 'Спис.ДЗ: 3.Ликв.ЮЛ (ст.419 ГК РФ)-62 сч(нет докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88031', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-76 сч(нет докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88030', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-76 сч(24-36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88029', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-76 сч(12-24 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88028', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-76 сч(12 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88027', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88026', 'Спис.ДЗ: 2.Смерть гражд(ст.418, 1175 ГК РФ)-62 сч(нет.докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88025', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-76 сч(нет докум. или свыше 36мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88024', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-76 сч(24-36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88023', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-76 сч(12-24 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88022', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-76 сч(12 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88021', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88020', 'Спис.ДЗ: 1.ИСИД (3 года, ст.196 ГК РФ)-62 сч(нет докум. или свыше 36 мес)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88019', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ: 2. Смерть гражданина (ст.418, 1175 ГК РФ)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88018', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ: 7. Пост.СП об окончании ИП и возвр.исп. док-та (абз.2,3,4 п', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88017', 'Спис.ДЗ: 7.Пост.суд.пристава(абз.2,3,4 п.2 ст.266 НК РФ)-62 сч(отч. или 36 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88016', 'Списание ДЗ сторонних организаций', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88015', 'ЗАКРЫТО ДЛЯ ИСП-Я ликвидация юр.лица или смерть физ.лица', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88014', 'Спис.ДЗ: 5.На основании акта гос.органа (ст.417 ГК РФ)-62 сч(отч.год или 36 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88013', 'Спис.ДЗ: 4.Невозм.исполн.обяз-ва(ст.416 ГК РФ)-62 сч(отч.год или 36 мес.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88012', 'ЗАКРЫТО ДЛЯ ИСП-Я истекший срок исковой давности', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88007', 'Вывод в ИСУП Axapta', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88005', 'Возврат клиенту', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88002', 'Ошибка ввода', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77025', 'Автоматический перерасчет (вызовы предыдущих периодов)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77024', 'Ком: Услуги / доп. опции по акции', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77023', 'Ком: Форс-мажорные обстоятельства', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77022', 'Ком: Благотворительность', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77021', 'Ком: 9 мая', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77020', 'Автоматический перерасчет', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77019', 'Пр: Несанкционированный доступ 3-их лиц к услугам', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77018', 'Пр: Сверка с операторами / посредниками', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77017', 'Пр: Гос. пошлина', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77016', 'Пр: По решению судебных и надзорных органов', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77015', 'Ош: Неправомерные начисления в период блокировки', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77014', 'Ош: Ошибки сотрудника ТБ', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77013', 'Ош: Ошибки тарификации (ИТ)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77012', 'Ош: Несвоевременное назначение / снятие услуги', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77011', 'Ош: Ошибка при изменении условий договора', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77010', 'Ош: Ошибка при заведении новых ТП в ИС', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77009', 'АО: Изменение условий оплаты за оборудование', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77008', 'АО: Возврат/замена оборудования', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77007', 'Фин: Корректировка пени', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77006', 'Фин: Перенос начислений', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77005', 'Тех: Тестовое подключение', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77004', 'Тех: Некачественное оказание услуги', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77003', 'Тех: Отсутствие услуги', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77002', 'Ком: Доначисления за нарушения условий акции', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77001', 'Ком: Индивидуальная (разовая) корректировка', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('50002', 'Миграция в САПРП', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('50001', 'Миграция в САПРП', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('40001', 'Ошибка ЕСПП', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('9999', 'Перенос баланса с', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('9998', 'Перенос баланса на', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('9997', 'Перенос аванса с неосновного типа счета', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('1047', 'Спис.ДЗ: акция 9 мая', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('1036', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание КЗ РТК свыше 3-х лет', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('1706', 'Доходы от розничной торговли товарами, связанными с услугами связи  15% взносом при расср', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('42', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание ДЗ: 4. Невозможность исполнения обязательства (ст.416 ГК РФ)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('22', 'Тест', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('21', 'Признак корректировки платежей', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('2', 'Пересчет ВНРН по факту приема раннего платежа', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('1', 'Обнуление баланса RT-клиента', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('0', '???', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('1012', 'ЗАКРЫТО ДЛЯ ИСП-Я РТК Списание ДЗ свыше 3-х лет', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('967', 'ЗАКРЫТО ДЛЯ ИСП-Я Списание КЗ РТК', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('853', 'Спис.ДЗ: 6.НСДЗ', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('794', 'Коммунальные услуги', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('782', 'Услуга зонового инициирования вызова с сети другого оператора  - за пределами территории о', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('505', 'Автом. исх./вх. справка', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('160000', 'test111', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('66003', 'Передача ДЗ по ВХР из МРФ УРАЛ/конвергент', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88063', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-62 сч(нет докум.или свыше 36м)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('66002', 'Передача КЗ по ВХР в МРФ УРАЛ/конвергент', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77028', 'Ош: Ошибки тарификации (сбой системы)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88006', 'Исходящая БС', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88062', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-62 сч(отч.год или 36м.до отч.г.)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88064', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-76 сч(отчетный год)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88066', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-76 сч(12-24 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88065', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-76 сч(12 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88067', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-76 сч(24-36 м.до отч.года)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('88068', 'Спис.ДЗ: 8. Обяз-во прекращ.вслед.банкр.граж(ФЗ N 127-ФЗ)-76 сч(нет докум.или свыше 36м)', true, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('77027', 'Фин - м: Перенос начислений', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('44001', 'Отмена списания ЕСПП кредитной схемы', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('99016', 'Спис.ДЗ: (ТОЛЬКО для КОМИ пр-во34,36,40)1.ИСИД(3 г,ст.196 ГК РФ)-76 сч(отчетный год)', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('60001', 'Начисления из внешней ИС ДЗО', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp),
('66001', 'Передача ДЗ по ВХР в МРФ  УРАЛ/конвергент', false, 'SZT_ALL_BIS_X_ADJUST_REASONS_FIELD', current_timestamp,current_timestamp);
$$ 
END
